# Auto-generated module
# CHECKLINE 2024-12-20 12:16:22

from simple_money_lib.currency import Currency as _Currency
from simple_money_lib.currencies.currency_collections import CurrencyCollection as _CurrencyCollection

# Export individual currencies
AED = _Currency("AED")
AFN = _Currency("AFN")
ALL = _Currency("ALL")
AMD = _Currency("AMD")
ANG = _Currency("ANG")
AOA = _Currency("AOA")
ARS = _Currency("ARS")
AUD = _Currency("AUD")
AWG = _Currency("AWG")
AZN = _Currency("AZN")
BAM = _Currency("BAM")
BBD = _Currency("BBD")
BDT = _Currency("BDT")
BGN = _Currency("BGN")
BHD = _Currency("BHD")
BIF = _Currency("BIF")
BMD = _Currency("BMD")
BND = _Currency("BND")
BOB = _Currency("BOB")
BOV = _Currency("BOV")
BRL = _Currency("BRL")
BSD = _Currency("BSD")
BTN = _Currency("BTN")
BWP = _Currency("BWP")
BYN = _Currency("BYN")
BZD = _Currency("BZD")
CAD = _Currency("CAD")
CDF = _Currency("CDF")
CHE = _Currency("CHE")
CHF = _Currency("CHF")
CHW = _Currency("CHW")
CLF = _Currency("CLF")
CLP = _Currency("CLP")
CNY = _Currency("CNY")
COP = _Currency("COP")
COU = _Currency("COU")
CRC = _Currency("CRC")
CUP = _Currency("CUP")
CVE = _Currency("CVE")
CZK = _Currency("CZK")
DJF = _Currency("DJF")
DKK = _Currency("DKK")
DOP = _Currency("DOP")
DZD = _Currency("DZD")
EGP = _Currency("EGP")
ERN = _Currency("ERN")
ETB = _Currency("ETB")
EUR = _Currency("EUR")
FJD = _Currency("FJD")
FKP = _Currency("FKP")
GBP = _Currency("GBP")
GEL = _Currency("GEL")
GHS = _Currency("GHS")
GIP = _Currency("GIP")
GMD = _Currency("GMD")
GNF = _Currency("GNF")
GTQ = _Currency("GTQ")
GYD = _Currency("GYD")
HKD = _Currency("HKD")
HNL = _Currency("HNL")
HTG = _Currency("HTG")
HUF = _Currency("HUF")
IDR = _Currency("IDR")
ILS = _Currency("ILS")
INR = _Currency("INR")
IQD = _Currency("IQD")
IRR = _Currency("IRR")
ISK = _Currency("ISK")
JMD = _Currency("JMD")
JOD = _Currency("JOD")
JPY = _Currency("JPY")
KES = _Currency("KES")
KGS = _Currency("KGS")
KHR = _Currency("KHR")
KMF = _Currency("KMF")
KPW = _Currency("KPW")
KRW = _Currency("KRW")
KWD = _Currency("KWD")
KYD = _Currency("KYD")
KZT = _Currency("KZT")
LAK = _Currency("LAK")
LBP = _Currency("LBP")
LKR = _Currency("LKR")
LRD = _Currency("LRD")
LSL = _Currency("LSL")
LYD = _Currency("LYD")
MAD = _Currency("MAD")
MDL = _Currency("MDL")
MGA = _Currency("MGA")
MKD = _Currency("MKD")
MMK = _Currency("MMK")
MNT = _Currency("MNT")
MOP = _Currency("MOP")
MRU = _Currency("MRU")
MUR = _Currency("MUR")
MVR = _Currency("MVR")
MWK = _Currency("MWK")
MXN = _Currency("MXN")
MXV = _Currency("MXV")
MYR = _Currency("MYR")
MZN = _Currency("MZN")
NAD = _Currency("NAD")
NGN = _Currency("NGN")
NIO = _Currency("NIO")
NOK = _Currency("NOK")
NPR = _Currency("NPR")
NZD = _Currency("NZD")
OMR = _Currency("OMR")
PAB = _Currency("PAB")
PEN = _Currency("PEN")
PGK = _Currency("PGK")
PHP = _Currency("PHP")
PKR = _Currency("PKR")
PLN = _Currency("PLN")
PYG = _Currency("PYG")
QAR = _Currency("QAR")
RON = _Currency("RON")
RSD = _Currency("RSD")
RUB = _Currency("RUB")
RWF = _Currency("RWF")
SAR = _Currency("SAR")
SBD = _Currency("SBD")
SCR = _Currency("SCR")
SDG = _Currency("SDG")
SEK = _Currency("SEK")
SGD = _Currency("SGD")
SHP = _Currency("SHP")
SLE = _Currency("SLE")
SOS = _Currency("SOS")
SRD = _Currency("SRD")
SSP = _Currency("SSP")
STN = _Currency("STN")
SVC = _Currency("SVC")
SYP = _Currency("SYP")
SZL = _Currency("SZL")
THB = _Currency("THB")
TJS = _Currency("TJS")
TMT = _Currency("TMT")
TND = _Currency("TND")
TOP = _Currency("TOP")
TRY = _Currency("TRY")
TTD = _Currency("TTD")
TWD = _Currency("TWD")
TZS = _Currency("TZS")
UAH = _Currency("UAH")
UGX = _Currency("UGX")
USD = _Currency("USD")
USN = _Currency("USN")
UYI = _Currency("UYI")
UYU = _Currency("UYU")
UYW = _Currency("UYW")
UZS = _Currency("UZS")
VED = _Currency("VED")
VES = _Currency("VES")
VND = _Currency("VND")
VUV = _Currency("VUV")
WST = _Currency("WST")
XAF = _Currency("XAF")
XAG = _Currency("XAG")
XAU = _Currency("XAU")
XBA = _Currency("XBA")
XBB = _Currency("XBB")
XBC = _Currency("XBC")
XBD = _Currency("XBD")
XCD = _Currency("XCD")
XDR = _Currency("XDR")
XOF = _Currency("XOF")
XPD = _Currency("XPD")
XPF = _Currency("XPF")
XPT = _Currency("XPT")
XSU = _Currency("XSU")
XTS = _Currency("XTS")
XUA = _Currency("XUA")
XXX = _Currency("XXX")
YER = _Currency("YER")
ZAR = _Currency("ZAR")
ZMW = _Currency("ZMW")
ZWG = _Currency("ZWG")

all_iso_currencies = _CurrencyCollection(
    AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF,
    BMD, BND, BOB, BOV, BRL, BSD, BTN, BWP, BYN, BZD, CAD, CDF, CHE, CHF, CHW, CLF,
    CLP, CNY, COP, COU, CRC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, EUR,
    FJD, FKP, GBP, GEL, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HTG, HUF, IDR, ILS,
    INR, IQD, IRR, ISK, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT,
    LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR,
    MWK, MXN, MXV, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP,
    PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, SEK, SGD, SHP, SLE,
    SOS, SRD, SSP, STN, SVC, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TWD, TZS,
    UAH, UGX, USD, USN, UYI, UYU, UYW, UZS, VED, VES, VND, VUV, WST, XAF, XAG, XAU,
    XBA, XBB, XBC, XBD, XCD, XDR, XOF, XPD, XPF, XPT, XSU, XTS, XUA, XXX, YER, ZAR,
    ZMW, ZWG,
    name="all_iso_currencies",
    description="Includes all ISO currencies, source: https://en.wikipedia.org/wiki/ISO_4217"
)

__all__ = ["AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF",
    "BMD", "BND", "BOB", "BOV", "BRL", "BSD", "BTN", "BWP", "BYN", "BZD", "CAD", "CDF", "CHE", "CHF", "CHW", "CLF",
    "CLP", "CNY", "COP", "COU", "CRC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR",
    "FJD", "FKP", "GBP", "GEL", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HTG", "HUF", "IDR", "ILS",
    "INR", "IQD", "IRR", "ISK", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT",
    "LAK", "LBP", "LKR", "LRD", "LSL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRU", "MUR", "MVR",
    "MWK", "MXN", "MXV", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP",
    "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE",
    "SOS", "SRD", "SSP", "STN", "SVC", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS",
    "UAH", "UGX", "USD", "USN", "UYI", "UYU", "UYW", "UZS", "VED", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU",
    "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XOF", "XPD", "XPF", "XPT", "XSU", "XTS", "XUA", "XXX", "YER", "ZAR",
    "ZMW", "ZWG", 'all_iso_currencies']
